<h3>Promo&#231;&#227;o Sistema Operacional Mozilla Firefox</h3>
<h4>REGULAMENTO OFICIAL</h4>

<p>A Promo&#231;&#227;o a seguir destina-se a ser exibida no Brasil, e foi criada e avaliada de acordo com as leis aplic&#225;veis. N&#227;o participe desta Promo&#231;&#227;o caso n&#227;o seja residente legal e localizado no Brasil no momento da inscri&#231;&#227;o.</p>

<p><strong>N&#195;O &#201; NECESS&#193;RIO COMPRAR OU REALIZAR QUALQUER PAGAMENTO PARA PARTICIPAR OU GANHAR. UMA COMPRA E/OU QUALQUER TIPO DE PAGAMENTO N&#195;O AUMENTAM SUAS CHANCES DE GANHAR.</strong></p>

<p><strong>ESTA PROMO&#199;&#195;O N&#195;O CONSTITUI SORTEIO, SENDO EM VEZ DISSO UM CONCURSO NO QUAL SER&#195;O JULGADOS DETERMINADOS FATORES, ESTABELECIDOS NESTE REGULAMENTO OFICIAL.</strong></p>

<p><strong>Ao participar da Promo&#231;&#227;o Sistema Operacional Mozilla Firefox (a "Promo&#231;&#227;o"), cada inscrito ("Inscrito" e coletivamente "Inscritos") aceita e concorda incondicionalmente em cumprir e seguir este Regulamento Oficial e as decis&#245;es dos ju&#237;zes, que s&#227;o definitivas e vinculativas em todos os aspectos. Esta Promo&#231;&#227;o &#233; patrocinada pela Mozilla Corporation ("Patrocinador"). Esta Promo&#231;&#227;o n&#227;o &#233; patrocinada, endossada,
administrada ou associada ao Twitter. O Twitter n&#227;o possui qualquer responsabilidade relacionada a esta Promo&#231;&#227;o. Para participar, os Inscritos devem atender a todos os requisitos estabelecidos neste Regulamento Oficial.</strong></p>

<p><strong>1. ELEGIBILIDADE:</strong> A Promo&#231;&#227;o est&#225; aberta somente a residentes legais do Brasil e que tenham 18 anos de idade ou mais. As inscri&#231;&#245;es recebidas dos residentes legais de qualquer pa&#237;s n&#227;o especificado aqui ser&#227;o inv&#225;lidas. Os funcion&#225;rios do Patrocinador e suas empresas matriz, afiliadas, subsidi&#225;rias, empresas relacionadas, ag&#234;ncias e parentes diretos (definidos como pais, filhos, irm&#227;os e c&#244;njuges e seus respectivos c&#244;njuges, independente de onde quer que residam) e aquelas pessoas que moram na mesma resid&#234;ncia, sejam elas parentes ou n&#227;o, n&#227;o s&#227;o eleg&#237;veis para se inscrever ou ganhar. Esta Promo&#231;&#227;o n&#227;o &#233; v&#225;lida onde for proibida ou restrita por lei.</p>

<p><strong>2. CONDI&#199;&#213;ES DE INSCRI&#199;&#195;O: </strong> Para se inscrever na Promo&#231;&#227;o, &#233; necess&#225;rio ter acesso &#224; Internet e uma conta v&#225;lida no Twitter. As contas do Twitter s&#227;o gratuitas. As pessoas eleg&#237;veis podem se registrar em HYPERLINK "https://twitter.com" <u>https://twitter.com</u>. Ao enviar suas informa&#231;&#245;es e criar uma conta no Twitter, o usu&#225;rio concorda com os Termos de Servi&#231;o do Twitter dispon&#237;veis em HYPERLINK "https://twitter.com/tos" <u>https://twitter.com/tos</u> e com a Pol&#237;tica de Privacidade dispon&#237;vel em HYPERLINK "https://twitter.com/privacy"    <u>https://twitter.com/privacy</u>. O titular autorizado da conta do Twitter e propriet&#225;rio do endere&#231;o de e-mail associado &#224; conta do Twitter usada para se inscrever na Promo&#231;&#227;o &#233; considerado o Inscrito. O "titular autorizado da conta" &#233; a pessoa f&#237;sica atribu&#237;da &#224; conta do Twitter pelo Twitter. Cada vencedor em potencial poder&#225; precisar apresentar comprova&#231;&#227;o de ser o titular autorizado da conta. Ap&#243;s um Inscrito fazer login em sua conta do Twitter v&#225;lida, o Inscrito deve se tornar seguidor de @MozillaBrasil e/ou @FirefoxBrasil e seguir as instru&#231;&#245;es a seguir para participar. O limite &#233; de tr&#234;s (3) Participa&#231;&#245;es por pessoa por toda a dura&#231;&#227;o da Promo&#231;&#227;o. Qualquer Participa&#231;&#227;o subsequente ser&#225; desqualificada. O tweet do Inscrito, juntamente com qualquer foto ou v&#237;deo opcional, &#233; considerada uma participa&#231;&#227;o (<strong>"Participa&#231;&#227;o"</strong>).O Twitter n&#227;o &#233; patrocinador de @MozillaBrasil ou @FirefoxBrasil ou da Promo&#231;&#227;o.</p>

<p>Cada Participa&#231;&#227;o enviada (i) deve estar de acordo com a imagem do Patrocinador (conforme determinado pelo Patrocinador a seu pr&#243;prio crit&#233;rio), (ii) n&#227;o poder&#225; ser inadequada, ofensiva, caluniosa, difamat&#243;ria, pornogr&#225;fica, sexualmente expl&#237;cita, conter nudez, ser ilegal ou pl&#225;gio, (iii) n&#227;o poder&#225; conter ass&#233;dio, ser ofensiva, amea&#231;adora, prejudicial, vulgar, conter palavr&#245;es, ser obscena, excessivamente violenta, ser censur&#225;vel ou ofensiva do ponto de vista racial, &#233;tnico ou qualquer outro, (iv) n&#227;o poder&#225; infringir nem encorajar terceiros a infringir qualquer lei, estatuto, decreto ou regulamento, (v) n&#227;o poder&#225; difamar ou violar os direitos de publicidade ou privacidade de qualquer pessoa, viva ou falecida, ou de qualquer outra forma infringir os direitos pessoais ou de
propriedade de qualquer pessoa ou terceiros, (vi) n&#227;o poder&#225; conter propaganda comercial ou corporativa, incluindo exibi&#231;&#227;o de logotipos, marcas e slogans corporativos, (vii) n&#227;o poder&#225; incluir refer&#234;ncias a bebidas alco&#243;licas, tabaco, apetrechos relacionados ao uso de drogas, armas de fogo ou qualquer descri&#231;&#227;o ou representa&#231;&#227;o dos mesmos, (viii) n&#227;o poder&#225; incluir refer&#234;ncias a qualquer um dos concorrentes do Patrocinador (incluindo qualquer outro fabricante ou distribuidor de sistemas operacionais para celular, navegadores de internet e ferramentas de internet) e (ix) n&#227;o poder&#225; incluir link para qualquer site que inclua v&#237;rus, worm, arquivo corrompido, cavalo de tr&#243;ia ou outras formas de c&#243;digo ou conte&#250;do corruptor, que possa causar danos ou comprometer o site do Patrocinador ou a conduta apropriada da Promo&#231;&#227;o. O Patrocinador reserva-se o direito de confirmar se qualquer informa&#231;&#227;o contida em uma Participa&#231;&#227;o enviada &#233; precisa ou verdadeira. O Patrocinador tem o direito, a seu pr&#243;prio crit&#233;rio, de determinar se qualquer Participa&#231;&#227;o &#233; inapropriada para inclus&#227;o na Promo&#231;&#227;o ou se n&#227;o est&#225; de acordo com este Regulamento Oficial. O Patrocinador reserva-se o direito de desqualificar qualquer Participa&#231;&#227;o por qualquer motivo, a qualquer momento. As decis&#245;es do Patrocinador s&#227;o definitivas e vinculativas, no que diz respeito a todas as quest&#245;es relacionadas a esta Promo&#231;&#227;o.</p>

<p><strong>3. PER&#205;ODO:</strong> A Promo&#231;&#227;o come&#231;a em 24 de mar&#231;o de 2014 &#224;s 12:00, hor&#225;rio da costa leste dos EUA (EDT)<strong>,</strong> e termina em 21 de abril de 2014 &#224;s 12:00, hor&#225;rio da costa leste dos EUA (EDT)(o "<strong>Per&#237;odo da Promo&#231;&#227;o</strong>"). Para serem eleg&#237;veis, as Participa&#231;&#245;es devem ser enviadas durante o Per&#237;odo da Promo&#231;&#227;o.</p>

<p><strong>4. COMO SE INSCREVER</strong>: Para participar, os Inscritos devem seguir @MozillaBrasil e/ou @FirefoxBrasil e enviar um tweet escrito (obrigat&#243;rio) que atenda &#224;s condi&#231;&#245;es abaixo:</p>

<ol start="4" type="1">
    <ol start="1" type="a">
        <li>N&#227;o deve exceder cento e quarenta (140) caracteres em um (1) tweet;</li>
        <li>Deve conter "#FirefoxOS";</li>
        <li>Deve responder &#224; pergunta semanal da Promo&#231;&#227;o, feita em um tweet pelas contas @MozillaBrasil e @FirefoxBrasil a cada semana;</li>
        <li>Deve ser respondida de forma p&#250;blica (por exemplo, a Participa&#231;&#227;o n&#227;o pode ser postada para contas privadas do Twitter);</li>
        <li>Deve ser em portugu&#234;s, e</li>
        <li>Deve ser escrita por voc&#234;.</li>
    </ol>
</ol>

<p>Al&#233;m da parte escrita obrigat&#243;ria de uma Participa&#231;&#227;o, os Inscritos podem enviar um v&#237;deo ou fotos (ambos s&#227;o opcionais). Se inclu&#237;dos, eles devem atender &#224;s condi&#231;&#245;es a seguir:</p>

<p><strong>V&#237;deo (opcional):</strong></p>

<p><strong>a.</strong> O v&#237;deo n&#227;o pode exceder quinze (15) segundos de dura&#231;&#227;o. Se for mais longo do que 15 segundos, apenas os primeiros 15 segundos ser&#227;o avaliados;</p>

<p><strong>b.</strong> O v&#237;deo deve ter tem&#225;tica n&#227;o comercial (por exemplo, o v&#237;deo n&#227;o pode ser um comercial de televis&#227;o ou propaganda de um produto ou servi&#231;o);</p>

<p><strong>c.</strong> O v&#237;deo pode ser inclu&#237;do atrav&#233;s de um link para um site de terceiros;</p>

<p><strong>d.</strong> O v&#237;deo deve ser de sua pr&#243;pria cria&#231;&#227;o;</p>

<p><strong>e.</strong> O v&#237;deo n&#227;o pode incluir qualquer propriedade intelectual n&#227;o autorizada de terceiros (como logotipos, clipes de v&#237;deo ou m&#250;sica), e</p>

<p><strong>f.</strong> Se alguma pessoa aparecer no v&#237;deo, voc&#234; deve ter a permiss&#227;o dela para enviar o v&#237;deo para a Promo&#231;&#227;o.</p>

<p><strong>Fotos (opcional):</strong></p>

<p><strong>a.</strong> A participa&#231;&#227;o n&#227;o pode conter mais de 5 fotos. Se contiver mais do que 5 fotos, apenas as primeiras 5 ser&#227;o avaliadas;</p>

<p><strong>b.</strong> As fotos devem ser em formato .jpg, .gif ou .png com tamanho m&#225;ximo de arquivo de cinco (5) MB/cada;</p>

<p><strong>c.</strong> As fotos podem ser inclu&#237;das atrav&#233;s de um link para um site de terceiros;</p>

<p><strong>d.</strong> As fotos devem ser de sua pr&#243;pria cria&#231;&#227;o;</p>

<p><strong>e.</strong> As fotos n&#227;o podem incluir qualquer propriedade intelectual n&#227;o autorizada de terceiros (como fotos tiradas por outra pessoa), e</p>

<p><strong>f.</strong> Se alguma pessoa aparecer nas fotos, voc&#234; deve ter a permiss&#227;o dela para enviar as fotos para a Promo&#231;&#227;o.</p>

<p><strong>5. </strong> <strong>SELE&#199;&#195;O DO VENCEDOR</strong>: Quando a Promo&#231;&#227;o terminar, um j&#250;ri de profissionais de m&#237;dia analisar&#225; e julgar&#225; as Participa&#231;&#245;es e selecionar&#225; oito (8) vencedores do primeiro lugar e oito (8) vencedores do segundo lugar, para um total de dezesseis (16) vencedores. Os vencedores ser&#227;o selecionados com base nos seguintes crit&#233;rios de julgamento: 1) N&#237;vel de paix&#227;o na miss&#227;o do sistema operacional Firefox (40%); 2) Criatividade (30%) e 3) Originalidade (30%). Os Inscritos est&#227;o sujeitos &#224; confirma&#231;&#227;o de que s&#227;o qualificados a participar e ganhar, conforme definido neste Regulamento Oficial. O Patrocinador reserva-se o direito de desqualificar qualquer Participante por violar este Regulamento Oficial.</p>

<p><strong>6. PR&#202;MIOS</strong>: Oito (8) Pr&#234;mios de Primeiro Lugar: Um celular LG com Firefox OS (valor de varejo aproximado R$479). Oito (8) Pr&#234;mios de Segundo Lugar: Um celular Alcatel com Firefox OS (valor de varejo aproximado R$ 359). Valor de varejo total aproximado de todos os pr&#234;mios: R$ 6704<em>.</em>    Cada vencedor &#233; respons&#225;vel por obter seu pr&#243;prio contrato de servi&#231;os e plano de dados com uma operadora de celular para usar o telefone.Os pr&#234;mios ser&#227;o fornecidos de acordo com sua disponibilidade. Aguarde cinco (5) semanas at&#233; a entrega do pr&#234;mio desde o momento em que o vencedor fornecer as informa&#231;&#245;es de entrega ao Patrocinador. Os impostos sobre o pr&#234;mio, se houver, s&#227;o de exclusiva responsabilidade do vencedor. O Patrocinador recomenda que os Inscritos consultem um contador se tiverem alguma d&#250;vida sobre impostos. O patrocinador reserva-se o direito de substituir um pr&#234;mio por outro de valor igual ou superior a seu pr&#243;prio crit&#233;rio, se o pr&#234;mio anunciado estiver indispon&#237;vel. O Patrocinador n&#227;o precisa substituir um pr&#234;mio com base em solicita&#231;&#227;o do vencedor. Os pr&#234;mios s&#227;o intransfer&#237;veis. N&#227;o ser&#227;o concedidos pr&#234;mios em dinheiro. Ser&#227;o concedidos menos pr&#234;mios do que o n&#250;mero total anunciado caso seja enviado um n&#250;mero insuficiente de Participa&#231;&#245;es com qualidade suficiente.</p>

<p><strong>7. NOTIFICA&#199;&#195;O DO VENCEDOR: </strong> Dezesseis (16) Inscritos vencedores em potencial receber&#227;o uma mensagem direta (DM) no Twitter em ou pr&#243;ximo a 28 de abril de 2014. Os Inscritos vencedores em potencial devem responder &#224; mensagem direta (DM) no Twitter do Patrocinador atrav&#233;s de e-mail dentro de cinco (5) dias para serem eleg&#237;veis para ganhar, e tamb&#233;m devem responder ao e-mail subsequente do Patrocinador dentro de dois (2) dias com as informa&#231;&#245;es
solicitadas.Se um Inscrito vencedor em potencial n&#227;o responder dentro dos prazos acima ou for considerado pelo Patrocinador como n&#227;o qualificado para participar desta Promo&#231;&#227;o, o Inscrito vencedor em potencial ser&#225; desqualificado e um novo Inscrito vencedor em potencial ser&#225; selecionado. Os vencedores ser&#227;o anunciados atrav&#233;s do Twitter e em impactofirefoxos.com em ou pr&#243;ximo a 12 de maio de 2014.</p>

<p><strong>8. DOCUMENTA&#199;&#195;O NECESS&#193;RIA:</strong> O Inscrito vencedor em potencial pode precisar preencher uma Declara&#231;&#227;o de Elegibilidade e Libera&#231;&#227;o ("<strong>Declara&#231;&#227;o</strong>") de acordo com as instru&#231;&#245;es apresentadas na correspond&#234;ncia de notifica&#231;&#227;o. Qualquer Inscrito que n&#227;o o fizer ou recusar-se a assinar e devolver a documenta&#231;&#227;o necess&#225;ria dentro do per&#237;odo de tempo especificado pelo Patrocinador ser&#225; desqualificado. O n&#227;o cumprimento deste Regulamento Oficial ou n&#227;o enviar toda a documenta&#231;&#227;o necess&#225;ria no
prazo definido ou a incapacidade do Patrocinador de entrar em contato com um Inscrito (usando as informa&#231;&#245;es de contato fornecidas atrav&#233;s de sua conta no Twitter) dentro de um per&#237;odo de tempo razo&#225;vel, conforme determinado a crit&#233;rio exclusivo do Patrocinador, poder&#225; resultar em desqualifica&#231;&#227;o e perda do direito ao pr&#234;mio.</p>

<p><strong>9. PUBLICIDADE: </strong>Exceto onde proibido por lei, a participa&#231;&#227;o na Promo&#231;&#227;o constitui o consentimento do Inscrito ao uso pelo Patrocinador e seus agentes do nome do Inscrito, imagem, fotografia, voz, opini&#245;es e cidade e estado, participa&#231;&#245;es e tweets da Promo&#231;&#227;o para fins promocionais em qualquer m&#237;dia, no mundo inteiro, sem qualquer pagamento ou remunera&#231;&#227;o extra.</p>

<p><strong>10. CONDI&#199;&#213;ES GERAIS: </strong> Os Inscritos vencedores em potencial est&#227;o sujeitos &#224; verifica&#231;&#227;o do Patrocinador. As decis&#245;es do Patrocinador s&#227;o definitivas e vinculativas em todas as quest&#245;es relacionadas a esta Promo&#231;&#227;o. Os vencedores em potencial devem cumprir o Regulamento Oficial e o recebimento dos pr&#234;mios est&#225; condicionado &#224; satisfa&#231;&#227;o de todos os requisitos. O Patrocinador n&#227;o &#233; respons&#225;vel por falhas t&#233;cnicas, de hardware ou software, defeitos, perda ou indisponibilidade de conex&#245;es de rede ou transmiss&#245;es de computador falhas, incompletas, truncadas ou atrasadas, ou altera&#231;&#245;es imprevistas de calend&#225;rio que possam limitar a capacidade de um Inscrito participar da Promo&#231;&#227;o, mesmo que sejam causados por neglig&#234;ncia do Patrocinador. O Patrocinador, a seu pr&#243;prio crit&#233;rio, poder&#225; modificar, cancelar ou suspender esta Promo&#231;&#227;o em caso de v&#237;rus, bugs, interven&#231;&#245;es humanas n&#227;o autorizadas ou outras causas al&#233;m do controle do Patrocinador afetarem a administra&#231;&#227;o, seguran&#231;a ou desempenho apropriado da Promo&#231;&#227;o, ou se o Patrocinador tornar-se de outra maneira incapaz de conduzir a Promo&#231;&#227;o como planejado. O Patrocinador n&#227;o &#233; respons&#225;vel por altera&#231;&#245;es nas informa&#231;&#245;es de contato do Inscrito. N&#227;o ser&#227;o aceitas Participa&#231;&#245;es ileg&#237;veis ou incompletas.
Qualquer indiv&#237;duo que tentar ou de outra forma encorajar, direta ou indiretamente, o envio de participa&#231;&#245;es falsas, conforme determinado pelo Patrocinador, ser&#225; desqualificado. O Patrocinador poder&#225; desqualificar a seu pr&#243;prio crit&#233;rio qualquer Inscrito que interferir com o processo de inscri&#231;&#227;o.O Patrocinador, a seu pr&#243;prio crit&#233;rio, desqualificar&#225; os Inscritos que violarem este Regulamento Oficial, interferirem com a opera&#231;&#227;o da Promo&#231;&#227;o ou tiverem qualquer tipo de conduta prejudicial ou injusta para o Patrocinador, a Promo&#231;&#227;o ou qualquer outro Inscrito. O Patrocinador reserva-se o direito de fazer altera&#231;&#245;es neste Regulamento Oficial a qualquer momento. Se por algum motivo qualquer disposi&#231;&#227;o deste Regulamento Oficial for considerado inv&#225;lido, ilegal ou de outra maneira inexequ&#237;vel, este Regulamento Oficial ser&#225; aplicado at&#233; o m&#225;ximo permitido. O Patrocinador n&#227;o &#233; respons&#225;vel por
participa&#231;&#245;es atrasadas, n&#227;o entregues, perdidas, incompletas, extraviadas, redirecionadas, danificadas, odificadas, ileg&#237;veis, corrompidas ou sujeitas a qualquer outro problema, condi&#231;&#227;o ou evento al&#233;m do controle do Patrocinador. Sem limita&#231;&#227;o do exposto anteriormente, o Patrocinador n&#227;o tem controle sobre sistemas ou servi&#231;os fornecidos por terceiros, incluindo o Twitter e os provedores de servi&#231;o de Internet dos Inscritos, e n&#227;o &#233; respons&#225;vel por interrup&#231;&#245;es de servi&#231;o, quedas, perda de dados, erros de servidor, falhas de transmiss&#227;o ou qualquer outra dificuldade t&#233;cnica que possa afetar a participa&#231;&#227;o de um Inscrito nesta Promo&#231;&#227;o. Ap&#243;s o envio de uma Participa&#231;&#227;o, ela n&#227;o poder&#225; ser retirada, apagada, editada ou modificada de outra forma.</p>

<p>
<strong>11. DIREITOS NAS PARTICIPA&#199;&#213;ES</strong>: Cada Inscrito &#233; respons&#225;vel por sua Participa&#231;&#227;o e as consequ&#234;ncias de post&#225;-la ou public&#225;-la. Em rela&#231;&#227;o &#224; Participa&#231;&#227;o, cada Inscrito afirma, declara e garante que: (i) A Participa&#231;&#227;o &#233; obra original do Inscrito; (ii) a Participa&#231;&#227;o n&#227;o foi enviada a nenhum outro concurso ou para publica&#231;&#227;o em nenhum outro f&#243;rum; (iii) o Inscrito &#233; dono
ou tem as licen&#231;as, direitos, consentimentos, autoriza&#231;&#245;es e permiss&#245;es necess&#225;rios para usar a Participa&#231;&#227;o da maneira contemplada pelo Patrocinador; (iv) o Inscrito satisfez qualquer registro ou outros requisitos impostos pelas leis locais, estaduais, provinciais, municipais, nacionais ou internacionais aplic&#225;veis, e (v) o Inscrito obteve o consentimento, libera&#231;&#227;o e permiss&#227;o por escrito de cada e todo indiv&#237;duo identific&#225;vel na Participa&#231;&#227;o, para usar o nome ou a imagem de tal pessoa na Participa&#231;&#227;o e da maneira contemplada pelo Patrocinador.</p>

<p><strong>12. LICEN&#199;A:</strong> Ao enviar uma Participa&#231;&#227;o ao Patrocinador, o Inscrito concede, no limite m&#225;ximo permitido por lei, uma licen&#231;a livre de royalties, irrevog&#225;vel, perp&#233;tua e n&#227;o exclusiva ao Patrocinador, seus representantes designados, licenciados e afiliados ("<strong>Partes Autorizadas</strong>"), para reproduzir, distribuir, exibir, editar, modificar, adaptar, transferir, publicar, veicular, traduzir, duplicar, armazenar, copiar, executar em p&#250;blico, expor, criar obras derivadas, explorar e/ou usar ou reutilizar de qualquer outra forma (sem limite de tempo, maneira, frequ&#234;ncia de uso), atrav&#233;s de toda e qualquer m&#237;dia, sua Participa&#231;&#227;o e todos os elementos que a comp&#245;em, incluindo voz, a&#231;&#245;es, imagem, nome, apar&#234;ncia, material biogr&#225;fico, obras escritas do Inscrito e todas as outras informa&#231;&#245;es ou materiais que o Inscrito forneceu ou possa fornecer em conex&#227;o com esta Promo&#231;&#227;o em qualquer m&#237;dia, j&#225; conhecida ou concebida posteriormente, e de qualquer maneira, sem aprova&#231;&#227;o, permiss&#227;o ou considera&#231;&#227;o extra, perpetuamente em todo o universo. O Patrocinador n&#227;o tem qualquer obriga&#231;&#227;o de usar uma Participa&#231;&#227;o.</p>

<p><strong>13. LIBERA&#199;&#195;O:</strong> Como condi&#231;&#227;o para participar da Promo&#231;&#227;o, os Inscritos liberam as entidades da Promo&#231;&#227;o de toda e qualquer responsabilidade por perda, dano, defeito, preju&#237;zo, custo ou despesa, incluindo danos patrimoniais, ferimentos pessoais e morte que possam ocorrer em conex&#227;o, prepara&#231;&#227;o, viagem ou participa&#231;&#227;o da Promo&#231;&#227;o, ou posse, aceita&#231;&#227;o ou uso dos pr&#234;mios ou participa&#231;&#227;o em qualquer atividade relacionada &#224; Promo&#231;&#227;o, e reivindica&#231;&#245;es baseadas em direitos de publicidade,
infra&#231;&#227;o de direitos autorais ou marca comercial, difama&#231;&#227;o ou invas&#227;o de privacidade e entrega de mercadorias.</p>

<p><strong>14. LIMITA&#199;&#195;O DE RESPONSABILIDADE:</strong> O Patrocinador e suas respectivas afiliadas, subsidi&#225;rias, corpora&#231;&#245;es matriz, ag&#234;ncias de publicidade e promo&#231;&#227;o e todos os seus executivos, diretores, acionistas, funcion&#225;rios e agentes n&#227;o s&#227;o respons&#225;veis por: qualquer informa&#231;&#227;o de inscri&#231;&#227;o incorreta ou imprecisa; erros humanos; mau funcionamento t&#233;cnico; falhas, omiss&#245;es, interrup&#231;&#245;es, exclus&#245;es ou
defeitos de qualquer rede de telefonia, sistema on-line de computador, equipamento de computador, servidores, provedores ou software, incluindo qualquer preju&#237;zo ou dano ao computador do Inscrito ou de qualquer outra pessoa relacionado &#224; participa&#231;&#227;o ou incapacidade de participar da Promo&#231;&#227;o; incapacidade de acessar o site ou fazer o upload de informa&#231;&#245;es ou dados; roubo, adultera&#231;&#227;o, destrui&#231;&#227;o ou acesso ou altera&#231;&#227;o n&#227;o autorizados das participa&#231;&#245;es; dados processados tardiamente ou incorretamente ou que estejam incompletos ou tenham sido perdidos devido ao mau funcionamento de telefone, computador ou equipamentos eletr&#244;nicos, ou congest&#227;o do tr&#225;fego
em linhas telef&#244;nicas ou na Internet ou em qualquer site (incluindo o Twitter), ou por qualquer outro motivo; erros de impress&#227;o ou outros; ou qualquer combina&#231;&#227;o dos mesmos. A prova de upload de informa&#231;&#245;es ou dados ou de inser&#231;&#227;o de informa&#231;&#245;es no Twitter n&#227;o &#233; considerada prova de entrega ou recebimento. Participa&#231;&#245;es ileg&#237;veis, duplicadas e incompletas ser&#227;o desqualificadas. Participa&#231;&#245;es ou atos falsos, fraudulentos ou enganosos, conforme determinado pelo Patrocinador, tornam os Inscritos ineleg&#237;veis e todas as suas Participa&#231;&#245;es relacionadas inv&#225;lidas.</p>

<p><strong>15. COLETA DE INFORMA&#199;&#213;ES:</strong> As informa&#231;&#245;es coletadas em conex&#227;o com a Promo&#231;&#227;o ser&#227;o coletadas de acordo com a Pol&#237;tica de Privacidade doPatrocinador, dispon&#237;vel em HYPERLINK "http://www.mozilla.org/en-US/privacy/" <u>http://www.mozilla.org/en-US/privacy/</u>. Ao participar da Promo&#231;&#227;o, cada Inscrito concorda com os termos da Pol&#237;tica de Privacidade do Patrocinador. As informa&#231;&#245;es ser&#227;o coletadas com a finalidade &#250;nica de conceder pr&#234;mios e n&#227;o ser&#227;o divulgadas a terceiros, salvo ao realizar a entrega do pr&#234;mio ao Inscrito
vencedor.</p>

<p><strong>16. LEGISLA&#199;&#195;O VIGENTE: </strong> Todas as quest&#245;es e d&#250;vidas relacionadas &#224; constru&#231;&#227;o, validade, interpreta&#231;&#227;o e aplicabilidade desse Regulamento Oficial ou dos direitos e obriga&#231;&#245;es dos Inscritos ou do Patrocinador em rela&#231;&#227;o a esta Promo&#231;&#227;o s&#227;o regidas e interpretadas de acordo com as leis do Estado da Calif&#243;rnia (EUA), sem dar efeito a nenhum princ&#237;pio de op&#231;&#227;o ou conflito de leis (seja
do estado da Calif&#243;rnia ou de qualquer outra jurisdi&#231;&#227;o) que venha a causar a aplica&#231;&#227;o de leis de qualquer outra jurisdi&#231;&#227;o. No limite permitido pela legisla&#231;&#227;o aplic&#225;vel, se por algum motivo qualquer uma das disposi&#231;&#245;es deste Regulamento Oficial for considerada inv&#225;lida ou de outra forma inexequ&#237;vel nos termos das leis ou regulamentos locais, as demais disposi&#231;&#245;es deste Regulamento Oficial permanecer&#227;o em pleno vigor e efeito.</p>

<p><strong>17. PATROCINADOR:</strong> Mozilla Corporation, com sede localizada em 331 E. Evelyn Ave, Mountain View, CA 94041 EUA.</p>